# Generated by Django 6.0.2 on 2026-02-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelroom_image_url_alter_hotelroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='category',
            field=models.CharField(choices=[('LUXURY', 'Luxury'), ('DELUXE', 'Deluxe'), ('BUSINESS', 'Business'), ('ECONOMY', 'Economy'), ('STANDARD', 'Standard')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='food_menu',
            field=models.TextField(blank=True, help_text='JSON or text list of food items and prices'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='inclusions',
            field=models.TextField(blank=True, help_text='Comma-separated list of inclusions (e.g., Breakfast, Wifi)'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10),
        ),
    ]
