# Generated by Django 6.0.2 on 2026-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking_payment_status_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('category', models.CharField(choices=[('STARTER', 'Starter'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage'), ('SNACK', 'Snack')], default='MAIN_COURSE', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('PREPARING', 'Preparing'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='hotel.fooditem')),
            ],
        ),
    ]
